### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by tyfg6yugt** [spamgourmet/spamgourmet#18] opened 2022-02-22 01:15 UTC
Whenever i try to sign up it says internal server error in the website

**Comment by tyfg6yugt** [comment] 2022-02-22 01:16
i meant the website

**Comment by mikedlr** [comment] 2022-03-15 11:42
Works for me. Could you have cookies blocked or something similar? 

BTW - the correct support forum is the [support forum in the BBS](https://bbs.spamgourmet.com/) and not here. I'm going to close this ticket. If the problem is persisting for you could you please start a discussion on the board.

**Closed by mikedlr** 2022-03-15 11:42 UTC

**Comment by mikedlr** [comment] 2022-03-26 20:43
@tyfg6yugt there was a service crashing - it's been restarted but it could have been a problem for you at the time. Please try again and report if you have a problem.  The [discussion on the BBS](https://bbs.spamgourmet.com/viewtopic.php?f=4&t=1825&sid=46086c6d67e3d01837659f9029b34898) is here.

**Comment by tyfg6yugt** [comment] 2022-03-28 09:29
it works
